account/urls.py
from django.urls import path
from . import views

app_name = 'account'
urlpatterns = [
    path('register/',views.RejistView.as_view(),name = 'register_user'),
    path('login/',views.loginUserView.as_view(),name ='login_user'),
    path('logout/',views.logoutView.as_view(),name ='logout_user'),
    path('profile/<str:username>',views.UserProfile.as_view(),name= 'profile_user'),

            #change password khodam
#     path('send/',views.randomCode,name='random_code'),
#     path('change/',views.changepassword,name='done_code'),
            #change password django
    # path("reset/",views.ResetPasword.as_view(),name="reset_password"),
    # path("reset/done/",views.ResetPasswordDone.as_view(),name= "password_reset_done"),
    # path('confirm/<uidb64>/<token>/',views.ResetPasswordConfirm.as_view(),name = "reset_password_confirm"),
    # path('confirm/complete',views.ResetPasswordComplete.as_view(),name='password_reset_complete'),
]

myapp/urls.py
from django.urls import path
from . import views


app_name = 'home'
urlpatterns = [
    path ('',views.Home.as_view(),name ='home'),
    path ('post/<int:id>/<slug:slug>/',views.PostDetail.as_view(),name ='detail_post'),
    path('post/delete/<int:id>', views.DeletePost.as_view(), name='deletepost'),
    path('post/update/<int:id>',views.UpdatePost.as_view(),name = 'update_post'),
    path('post/create/',views.CreatePost.as_view(),name ='create_post')
]

pro/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('myapp.urls',namespace='home')),
    path('account/',include('account.urls',namespace='account'))
]

myapp/models.py
from django.db import models

# Create your models here.

myapp/forms.py
from django import forms
from account import models 


class PostCreateUpdateForm(forms.ModelForm):
    class Meta :
        model =  models.Post
        fields = ('body', )

myapp/views.py
from typing import Any
from django.shortcuts import render ,redirect,get_object_or_404
from django.http import HttpRequest, HttpResponse
from django.views import View
from account import models
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from . import forms
from django.utils.text import slugify
from django.contrib.auth.models import User


class Home(View):
    def get (self,request):
        post = models.Post.objects.order_by('-created','body',)
        return render(request , "home/index.html",{'post':post})
class PostDetail(View):
    def get(self,request, id, slug):
        post = get_object_or_404(models.Post,id=id,slug=slug)
        ctx = {
            'post':post,
        }
        return render(request,'home/detail.html', ctx)

class DeletePost(LoginRequiredMixin,View):
    def get(self,request,id):
        post = get_object_or_404(models.Post,id=id)
        username =request.user.username
        if post.user.username == request.user.username:
            post.delete()
            messages.success(request, 'پست شما با موفقیت حذف شد', 'warning') 
            
            return redirect('account:profile_user',username )
        else:
            messages.error(request, 'شما اجازه حذف این پست را ندارید', 'danger')
            return redirect('home:home')
class UpdatePost(LoginRequiredMixin, View):
    form_class = forms.PostCreateUpdateForm

    def setup(self, request: HttpRequest, *args: Any, **kwargs: Any) -> None:
        self.post_instance =get_object_or_404(models.Post,pk=kwargs['id'])
        return super().setup(request, *args, **kwargs)
    def dispatch(self, request, *args, **kwargs):
        post = self.post_instance
        if not post.user.username == request.user.username:
            messages.error(request, "شما اجازه ی تغییر این پست را ندارید",'danger')
            return redirect('home:home')
        return super().dispatch(request, *args, **kwargs)
    def get(self, request,*args,**kwargs):
        postt =self.post_instance
        form = self.form_class(instance=postt)
        return render(request,'home/update.html', {'form': form})

    def post (self,request,*args,**kwargs):
        post = self.post_instance
        form = self.form_class(request.POST , instance=post)
        if form.is_valid():
            form.save()
            messages.success(request,'پست شما با موفقیت تغییر یافت','success')
            return redirect ('home:detail_post',post.id,post.slug)
class CreatePost(View):
    form_class = forms.PostCreateUpdateForm
    def get(self ,request,*args, **kwargs):
        form =self.form_class()
        return render(request,'home/create.html',{'form':form})
    def post(self ,request,*args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid(): 
            newPost = form.save(commit=False)
            newPost.user = request.user
            newPost.save()
            messages.success(request,'پست شما با موفقیت ثبت شد','success') 
            return redirect ('home:detail_post',newPost.id , newPost.slug)
        return render(request,'home/create.html',{'form':form})
    

myapp/templates/home/create.html
{% extends "base.html" %}

{% block home %}
    <form method="post" novalidate>
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value = "ثبت پست "> 
    </form>
{% endblock %}

myapp/templates/home/detail.html
{% extends 'base.html' %}


{% block home %}
{% if post %}
    {% if request.user.id == post.user.id %}
        <div class="text-center">
            <a href="{% url 'home:deletepost' post.id %}" class="btn btn-danger">حذف</a>
            <a href="{% url 'home:update_post' post.id %}" class="btn btn-info btn-separator">ویرایش</a>
        </div>

    
    {% endif %}
    <h3 class = "text-center"><a href="{% url 'account:profile_user' post.user.username %}">{{ post.user }}</a></h3>
    <h3 class = "text-center">{{ post.user.email }}</h3><hr>
    <h5 class = "text-center">{{ post.body }}</h5><hr>
    <h5 class = "text-center">ایجاد شده در :</h5>
    <h5 class = "text-center">{{ post.updated|date:"Y-M-d" }}</h5><hr>
{% endif %}
{% endblock %}

myapp/templates/home/index.html
{% extends 'base.html' %}


{% block home %}
<div class = 'card'>
    {% for x in post %}
        <a href="{% url 'home:detail_post' x.id x.slug %}" class="card-body">{{x.body|truncatewords:6}}</a>
    {% endfor %}
</div>
{% endblock %}

myapp/templates/home/update.html
{% extends "base.html" %}

{% block home %}
    <form method="post" novalidate>
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value = "ثبت تغییرات"> 
    </form>
{% endblock %}