account/urls.py
from django.urls import path
from . import views

app_name = 'account'
urlpatterns = [
    path('register/',views.RejistView.as_view(),name = 'register_user'),
    path('login/',views.loginUserView.as_view(),name ='login_user'),
    path('logout/',views.logoutView.as_view(),name ='logout_user'),
    path('profile/<str:username>',views.UserProfile.as_view(),name= 'profile_user'),

            #change password khodam
#     path('send/',views.randomCode,name='random_code'),
#     path('change/',views.changepassword,name='done_code'),
            #change password django
    # path("reset/",views.ResetPasword.as_view(),name="reset_password"),
    # path("reset/done/",views.ResetPasswordDone.as_view(),name= "password_reset_done"),
    # path('confirm/<uidb64>/<token>/',views.ResetPasswordConfirm.as_view(),name = "reset_password_confirm"),
    # path('confirm/complete',views.ResetPasswordComplete.as_view(),name='password_reset_complete'),
]

myapp/urls.py
from django.urls import path
from . import views


app_name = 'home'
urlpatterns = [
    path ('',views.Home.as_view(),name ='home'),
    path ('post/<int:id>/<slug:slug>/',views.PostDetail.as_view(),name ='detail_post'),
    path('post/delete/<int:id>', views.DeletePost.as_view(), name='deletepost'),
    path('post/update/<int:id>',views.UpdatePost.as_view(),name = 'update_post'),
    path('post/create/',views.CreatePost.as_view(),name ='create_post')
]

pro/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('myapp.urls',namespace='home')),
    path('account/',include('account.urls',namespace='account'))
]

templates/inc/messages.html
{% if messages %}
    {% for msg in messages %}
        <p  class="alert alert-{{msg.tags}}">{{msg}}</p>
    {% endfor %}

{% endif %}

templates/inc/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <div class="navbar-nav text-center mx-auto">
            <a class="nav-link active" href="{% url 'home:home' %}">صفحه اصلی</a>
            {% if request.user.is_authenticated %}
                <a class="nav-link active" href="{% url 'account:profile_user' user.username %}">پروفایل</a>
                <a class="nav-link active" href="{% url 'account:logout_user' %}">خروج</a>
            {% else %}
                <a class="nav-link active" href="{% url 'account:register_user' %}">ثبت نام</a>
                <a class="nav-link active" href="{% url 'account:login_user' %}">ورود</a>
            {% endif %}
        </div>
    </div>
</nav>